In [ ]:
import numpy as np
import random
from scipy import ndimage

board = np.zeros([4,4])

def make_move(direction, free_spaces):
    if(direction == "w"):        
        for z in range(3):   
            for i in range(1,4,1):
                for j in range(4):
                    height = i
                    while(height>0):
                        if(board[i-1][j] == 0):
                            board[i-1][j] = board[i][j]  
                            board[i][j] = 0
                        elif(board[i-1][j] == board[i][j]):
                            board[i-1][j]*=2
                            board[i][j] = 0
                        height-=1
    
    if(direction == "s"):        
        for z in range(3):   
            for i in range(1,4,1):
                for j in range(4):
                    height = i
                    while(height<3):
                        if(board[i+1][j] == 0):
                            board[i+1][j] = board[i][j]  
                            board[i][j] = 0
                        elif(board[i+1][j] == board[i][j]):
                            board[i+1][j]*=2
                            board[i][j] = 0
                        height+=1
                        
    if(direction == "a"):        
        for z in range(3):   
            for i in range(4):
                for j in range(4):
                    height = j
                    while(height>0):
                        if(board[i][j-1] == 0):
                            board[i][j-1] = board[i][j]  
                            board[i][j] = 0
                        elif(board[i][j-1] == board[i][j]):
                            board[i][j-1]*=2
                            board[i][j] = 0
                        height-=1
    
    if(direction == "d"):        
        for z in range(3):   
            for i in range(4):
                for j in range(4):
                    height = j
                    while(height<3):
                        if(board[i][j+1] == 0):
                            board[i][j+1] = board[i][j]  
                            board[i][j] = 0
                        elif(board[i][j+1] == board[i][j]):
                            board[i][j+1]*=2
                            board[i][j] = 0
                        height+=1

    if(len(np.where(board.reshape(-1) == 0)[0])>0):
        spawn_number()
    

#If there are no free cells, checks if there are any possible moves before reporting game over
def multiple_unique_item(array):
    return len(np.unique(array)) > 1

def adjacent_diff(array):
    labeled_array, num_labels = ndimage.label(array)
    labels = np.arange(1, num_labels+1)
    any_multiple = ndimage.labeled_comprehension(array, labeled_array, labels, 
                                                 multiple_unique_item, bool, 0)
    return any_multiple.any()
    
    
    

def spawn_number():
    free_cells = np.where(board.reshape(-1) == 0)[0]
    if(len(free_cells) == 0 and not adjacent_diff):
        print("Game over!")
    else:
        
        rand = random.randint(0,len(free_cells)-1)

        if(random.random()<0.9):
            board.reshape(-1)[free_cells[rand]] = 2
        else:
            board.reshape(-1)[free_cells[rand]] = 4
    return(len(free_cells))
    
    


free_cells = spawn_number()
while(free_cells > 0):
    
    
    print(board)
    direction = input()
    make_move(direction, free_spaces)
    
    

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 0.]]
w
[[2. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 2.]]
w
[[2. 0. 2. 2.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
w
[[2. 0. 2. 2.]
 [0. 0. 0. 0.]
 [0. 0. 0. 4.]
 [0. 0. 0. 0.]]
w
[[2. 0. 2. 2.]
 [2. 0. 0. 4.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
w
[[4. 0. 2. 2.]
 [0. 0. 0. 4.]
 [0. 0. 0. 0.]
 [2. 0. 0. 0.]]
w
[[4. 0. 2. 2.]
 [2. 0. 0. 4.]
 [0. 0. 0. 0.]
 [0. 0. 4. 0.]]
w
[[4. 0. 2. 2.]
 [2. 0. 4. 4.]
 [0. 0. 0. 0.]
 [0. 0. 0. 2.]]
w
[[4. 0. 2. 2.]
 [2. 0. 4. 4.]
 [0. 0. 0. 2.]
 [0. 0. 0. 2.]]
w
[[4. 0. 2. 2.]
 [2. 0. 4. 8.]
 [2. 0. 0. 0.]
 [0. 0. 0. 0.]]
w
[[8. 0. 2. 2.]
 [0. 0. 4. 8.]
 [0. 0. 0. 0.]
 [2. 0. 0. 0.]]
w
[[8. 0. 2. 2.]
 [2. 0. 4. 8.]
 [2. 0. 0. 0.]
 [0. 0. 0. 0.]]
w
[[8. 0. 2. 2.]
 [4. 0. 4. 8.]
 [0. 0. 0. 0.]
 [2. 0. 0. 0.]]
w
[[8. 0. 2. 2.]
 [4. 0. 4. 8.]
 [2. 0. 0. 2.]
 [0. 0. 0. 0.]]
w
[[8. 0. 2. 2.]
 [4. 0. 4. 8.]
 [2. 0. 2. 2.]
 [0. 0. 0. 0.]]
w
[[8. 0. 2. 2.]
 [4. 0. 4. 8.]
 [2. 0. 2. 2.]
 [0. 2. 0.